# CMake generated Testfile for 
# Source directory: /home/pi/ros_catkin_ws/src/rosbridge_suite/rosbridge_library
# Build directory: /home/pi/ros_catkin_ws/build_isolated/rosbridge_library
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_rosbridge_library_rostest_test_capabilities_test_capabilities.test "/home/pi/ros_catkin_ws/build_isolated/rosbridge_library/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/ros_catkin_ws/build_isolated/rosbridge_library/test_results/rosbridge_library/rostest-test_capabilities_test_capabilities.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/pi/ros_catkin_ws/src/rosbridge_suite/rosbridge_library --package=rosbridge_library --results-filename test_capabilities_test_capabilities.xml --results-base-dir \"/home/pi/ros_catkin_ws/build_isolated/rosbridge_library/test_results\" /home/pi/ros_catkin_ws/src/rosbridge_suite/rosbridge_library/test/capabilities/test_capabilities.test ")
add_test(_ctest_rosbridge_library_rostest_test_internal_test_internal.test "/home/pi/ros_catkin_ws/build_isolated/rosbridge_library/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/ros_catkin_ws/build_isolated/rosbridge_library/test_results/rosbridge_library/rostest-test_internal_test_internal.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/pi/ros_catkin_ws/src/rosbridge_suite/rosbridge_library --package=rosbridge_library --results-filename test_internal_test_internal.xml --results-base-dir \"/home/pi/ros_catkin_ws/build_isolated/rosbridge_library/test_results\" /home/pi/ros_catkin_ws/src/rosbridge_suite/rosbridge_library/test/internal/test_internal.test ")
subdirs("gtest")
