set(_CATKIN_CURRENT_PACKAGE "agv2")
set(agv2_VERSION "0.0.0")
set(agv2_MAINTAINER "pi <pi@todo.todo>")
set(agv2_PACKAGE_FORMAT "2")
set(agv2_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "dynamic_reconfigure" "message_generation")
set(agv2_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "dynamic_reconfigure")
set(agv2_BUILDTOOL_DEPENDS "catkin")
set(agv2_BUILDTOOL_EXPORT_DEPENDS )
set(agv2_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "dynamic_reconfigure" "message_runtime")
set(agv2_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "dynamic_reconfigure" "message_runtime")
set(agv2_TEST_DEPENDS )
set(agv2_DOC_DEPENDS )
set(agv2_URL_WEBSITE "")
set(agv2_URL_BUGTRACKER "")
set(agv2_URL_REPOSITORY "")
set(agv2_DEPRECATED "")