// Generated by gencpp from file agv2/getparammResponse.msg
// DO NOT EDIT!


#ifndef AGV2_MESSAGE_GETPARAMMRESPONSE_H
#define AGV2_MESSAGE_GETPARAMMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv2
{
template <class ContainerAllocator>
struct getparammResponse_
{
  typedef getparammResponse_<ContainerAllocator> Type;

  getparammResponse_()
    : value(0)  {
    }
  getparammResponse_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef uint32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::agv2::getparammResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv2::getparammResponse_<ContainerAllocator> const> ConstPtr;

}; // struct getparammResponse_

typedef ::agv2::getparammResponse_<std::allocator<void> > getparammResponse;

typedef boost::shared_ptr< ::agv2::getparammResponse > getparammResponsePtr;
typedef boost::shared_ptr< ::agv2::getparammResponse const> getparammResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv2::getparammResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv2::getparammResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace agv2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::agv2::getparammResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv2::getparammResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv2::getparammResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv2::getparammResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv2::getparammResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv2::getparammResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv2::getparammResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9d213e8c146065ec958333c617eb1a6";
  }

  static const char* value(const ::agv2::getparammResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9d213e8c146065eULL;
  static const uint64_t static_value2 = 0xc958333c617eb1a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv2::getparammResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv2/getparammResponse";
  }

  static const char* value(const ::agv2::getparammResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv2::getparammResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 value\n\
";
  }

  static const char* value(const ::agv2::getparammResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv2::getparammResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getparammResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv2::getparammResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv2::getparammResponse_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV2_MESSAGE_GETPARAMMRESPONSE_H
