set(_CATKIN_CURRENT_PACKAGE "agv")
set(agv_VERSION "0.0.0")
set(agv_MAINTAINER "pi <pi@todo.todo>")
set(agv_PACKAGE_FORMAT "2")
set(agv_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(agv_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(agv_BUILDTOOL_DEPENDS "catkin")
set(agv_BUILDTOOL_EXPORT_DEPENDS )
set(agv_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(agv_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(agv_TEST_DEPENDS )
set(agv_DOC_DEPENDS )
set(agv_URL_WEBSITE "")
set(agv_URL_BUGTRACKER "")
set(agv_URL_REPOSITORY "")
set(agv_DEPRECATED "")